# Generated by Django 3.2.8 on 2021-10-27 12:17

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_group', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('user_ptr',
                 models.OneToOneField(auto_created=True,
                                      on_delete=django.db.models.deletion.CASCADE,
                                      parent_link=True,
                                      primary_key=True,
                                      serialize=False,
                                      to='auth.user')),
                ('user_image', models.ImageField(upload_to=None)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatUserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='messenger_app.chat')),
                ('chatuser', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='messenger_app.chatuser')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('chat', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='messenger_app.chat')),
                ('chatuser', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='messenger_app.chatuser')),
            ],
        ),
    ]
