# Generated by Django 3.2.8 on 2021-10-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('chat',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='messages',
                                   to='messenger_app.chat')),
                ('chatuser',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='messages',
                                   to='messenger_app.chatuser')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
