# Generated by Django 3.2.8 on 2021-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_app', '0002_auto_20211027_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='user_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
