apiVersion: v1
kind: Secret
metadata:
  name: secret-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewoJImF1dGhzIjogewoJCSIzNzE3MTMyNDM4MzAuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdz
    LmNvbSI6IHsKCQkJImF1dGgiOiAiUVZkVE9tVjVTbmRaV0d4ellqSkdhMGxxYjJsamJGWlVZbFYw
    ZDFSNlkzbGlWemg0WkZoUk1rNUdVa3RWYlU1M1pWUkNSMDFHWTNoVVNHeGhZMnBrUzFNd2NHeFhW
    ekUxWkc1b1JGcElRa1pqVlhRelkxWkNjMkZxWkhWT1JrcFJVVmhDVUUweGJIWlJWa295VFVkb2Ft
    RnJSblZrVlhSclZrZDRibUpFYTNobGJscDBZakJaY2xKNmFGbFpiR2hOVjFkc1YxcFhNVEZoYmtF
    MVVrVnNWbUZxVGtaVVJ6RlBWbXBTTlZWWE9EVlpha1pvWVZSb1NsZHFaRWhXUlRGMVYwUm9WVlJF
    V25GaVdIQlZVVEZDU1ZZd1RsWmxhelF6V2tab2RGWXhaRlZUYkZwTFUyMW9kbU15ZEV0YWJuQnpX
    bFJHUzFaNldYbFhSemxUWXpJMVVsSlVRbEZqYW1oNFpWVXhXazFIY3pWVWJrSTJUbTB4UzFOcVRs
    cFRSM1F3VmxoT1VVNHlhR0ZrVlVaeFRVVkpNR1ZxYUVsaE1IQk1WbFprVW1KcVNuVmlWVkpEWlZa
    c1RVd3pTbE5OTUZadlZtdE9UazFHUWxWYVJWSnhVa2hXVFZSVVRsVlBWbXhYVVd0d2IxRXhXbGhW
    TVdSS1pHeE9hRkZZWXpKYVJrcERVak5SZUZkR1FqWk9TR2gwWkdwWmNtTkdXblpaVjBac1RXeG9i
    RTU2VVhoaVZrbzBZbGhLVmxkV1p6Tk9NMEpGVVZSSk5VNUVRalZpUkZJd1ZXdDBObVZXVWtkU1J6
    bHZUREJ2Y21SclJqVlRlazQwWWpGdmVXRkVXa3BWUmxwc1RXdFJkMkZyYkRKVU1scHVWVlJzZVdK
    VlJsZGthMVZ5VVdwYVJsTldhSFZsVkZZMlVXNXNhMDVWVmxSYWFscDJWbTFyTkU1RlZrWmFTSEEw
    VGpCT1YyVnVVakJpVlRFMlZsWnNhazVXYUhaVlNFcEZVakJvV2xacmNFeFNWVlpVV2pGS2NHVldS
    a1JUUjFwR1lUSnNVRTFxV25kVU1FWkNWMWRXV21SclduZE9hMDVFV2pCc2FtUXdSVE5rVmtZeFRq
    SmpOR0pZUmxWYWFsVXdZa1pCTTJGSFdYaE9iVlUwVjFWYVZHRlhSblZVVkZKdFpHcGtkRmRzWTNs
    bGJXeEdTek5vTmxZeU1VcFViVnBTWVVSTk1HVkdjREJhTUhSMFZGVktURlY2U2xOVU1HTTFWbXhD
    Vm1OSGVFSlZiVW93VkVSb05tVlVaRFJWUnpGcFZWVmpNbEY2YkcxYU1tUlFWVVJHU0ZKWFNtaGhN
    MUoyVDFVNVEwMUZXbGxqYlhCRlkzcFdibUp1VG05VVdHUkhWMFJuY2xKV2JESldiRkV6V20wMVVt
    UjZXbkJsUm1STVZrZFNlVlpGVGpWVmF6QXhUbTAxZVZaSGFIbFVWMDVDVWtNNVNsSnJNREpPTWxK
    YVRtdGFkMVpVYkU5V1dHaFJZbTFhVFZwVVVUTmtSMlIyV1dwck0xSkVhRmhhU0hCdlZrY3hNVkZ0
    VGpCUlZFWlFWVVJaTW1JeFozWmFiR2hFWlZoU2VFMUVSalZPYm14SVRqSmFWV05GYXpCU1ZsbDVW
    bXM1VVdWVWJGTlBSVkpLWXpKYWNWbFVXa2xoYm1SUllsWldOV1JFUWtSYWFrWkZZVE5hZW1Wc2FE
    TkxNMDE0VmtoVmVGUnNjSEZUYlVwWFRrVk9iVlV3U2t0aWJUVk9WWHBXVG1Sc1FuQlZSMVpzVFhs
    MGNHUXpSbHBQVjJodFRsVkdlbVZIYkROa1JYQkxaRmhyZVZreVJsZFRSRUpDWTBSV1MxWXlOVVJa
    VjA1TFlXMHhTbVJIVWtwa2EwbzFZak5PZFUxSVVsWmpha3A2VmxaT2NGVXdNVzVrUjFKTllqRkpl
    VTlYTVUxTmF6RlJUVEJzYms1SGNIQldhMlJVV21wa1IyUkhXa2RYYTJRelZIcGplRmRxV2xWa01W
    WlZWbTVrUWxOSFdrUlZWVTVyVVd4T2JWZFlUbGhSYVhSU1lucENlRkpIWkVoa1F6bDBXakZPVW1W
    RVkzZFdSa294VWxSQmRtSXlUbGhhTURGNlpGaGtXa3N6Y0VsalZtaFhZbnBhZEdGSFZuUk5XR3hF
    V1RCa2FrMVljRmRoTUZwclRrZE5lV05GTld4WmJtUjJaREpTVkdGWFJucGxhM2g2V1cwNWFtUlZW
    akZOTWs0ellXNWFkRkZxV21oYVIyaENUVE5XVEZaSVRteFVSM0JNV2xaR1QwOUhXbWxoZWxwTFlV
    Wm9UMHd5U25WaFYydzJaVlZhTUdGNlFrZGliRWx5V2tkS1RWRlZjSE5aVkd4M1RVaE9hVXN4VlRK
    TE0wazBVMFYwV2xkSFpIWmtNRGxEVlVVMVdGcEhjR0ZpYm14c1pHcGplbEZxV2xGbFUzUlNUWHBr
    VG1JeFVqWlVXRVpLVFVoa1YxRlVNRGxKYVhkcFdrZEdNRmxYZEd4bFUwazJTV3RHVWxKVlNrSlRS
    Mmd6WWxSQ1dsbFZiRlJUYlZaVFpFVndkRTVYTkhoU2Vsb3hZMWRXYkdFeGFERmlNV2haVlVkVk1W
    WlZXbXBhVkd4VFkxUm5kazFVVWpOUlZVWkNVMFJTTTFwclJscFRhM1IyVjJ0c2IyUnRUazlSVmta
    cVVqSTVTRTlJWkdsVlZXeERVVlZTUTJJd1NtNWhNMFp2WVRKc1NFOVlZM2RSYTBvelVsaGtTVm94
    YkV0WFZXeGhVMVZHV0ZaVlVrTlJWVll4VkZWS1JsSlZVazlVUjA1elUwUm9SVlpVWkVaalZYY3hZ
    VEpLZFZGVmJFTlNWV3hDVGpKc2NrdDZaRkJVV0ZrelVsaHNjbUl6YkZGYVIyTXpUV3hKTkZreVZr
    TlZNVlpSVm10c1NFMVZUbEphUkZwcFZGVmtlVkpYVVhkaVdFNTFVbGRTVGxJd2FGUlRiWEJHVjFk
    U01GVnJaM0pTYWxKTVV6TlZlR1F5T1hwTlV6bE9WVlp3UmxZeFZsVlNiRVU1U1dsM2FXUnRWbmxq
    TW14MlltbEpOa2xxU1dsTVEwb3daVmhDYkVscWIybFNSVVpWVVZZNVRGSldhMmxNUTBwc1pVaENj
    R050UmpCaFZ6bDFTV3B2ZUU1cVRURk9lazAwVDBSck1tWlJQVDA9IgoJCX0KCX0KfQ==
