apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.3
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: postgres-pass
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: pg-database
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: pg-user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: pg-password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: messenger-secrets
                  key: db-port
          volumeMounts:
            - name: postgres-volume-mount
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
