Description: >
  Maged A. Saad / Messenger 2021

Parameters:
  VpcId:
    Description: description
    Type: String
  SubnetId:
    Description: description
    Type: String
  LoadBalancerARN:
    Description: description
    Type: String

Resources:
  LBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Sub "${VpcId}"
      TargetType: alb
      Protocol: TCP
      Port: 80
      Targets:
        - Id: !Sub "${LoadBalancerARN}"
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SubnetMappings:
        - SubnetId: !Sub "${SubnetId}"
          AllocationId: eipalloc-078366305465776e1 ## must be moved to parameter
      Type: network
  Listener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LBTargetGroup
      LoadBalancerArn: !Ref WebAppLB
      Port: "80"
      Protocol: TCP
