version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.3.0
  python: circleci/python@1.1.0

jobs:
  test-lint:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: ./messenger_api/requirements.txt
          pkg-manager: pip
      - python/install-packages:
          args: pylint
          pkg-manager: pip
      - run:
          command: |
            pylint messenger_api/*
          name: Test
  eksctl-install:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          command: |
            curl --location "https://github.com/weaveworks/eksctl/releases/download/v0.73.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            eksctl version
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - kubernetes/install
      - run:
          command: |
            source $BASH_ENV
      - run:
          command: |
            ./createStagingCluster.sh

workflows:
  test:
    jobs:
      - test-lint
